"use client";

import { App, Button, Card, Form, Input, InputNumber, Modal, Select, Space, Switch, Table, Tabs, Tag } from "antd";
import { useEffect, useState } from "react";

import { fetchAdminModelProviders, fetchAdminModelRoutes, fetchAdminModelVariants, saveAdminModelProvider, saveAdminModelRoute, saveAdminModelVariant, type AdminModelProvider, type AdminModelRoute, type AdminModelVariant } from "@/services/api/admin";
import { fetchModelMarket, type MarketModelCard } from "@/services/api/model-market";
import { useUserStore } from "@/stores/use-user-store";

export default function AdminModelRoutingPage() {
    const { message } = App.useApp();
    const token = useUserStore((state) => state.token);
    const [providers, setProviders] = useState<AdminModelProvider[]>([]);
    const [models, setModels] = useState<MarketModelCard[]>([]);
    const [routes, setRoutes] = useState<AdminModelRoute[]>([]);
    const [variants, setVariants] = useState<AdminModelVariant[]>([]);
    const [providerOpen, setProviderOpen] = useState(false);
    const [routeOpen, setRouteOpen] = useState(false);
    const [variantOpen, setVariantOpen] = useState(false);
    const [providerForm] = Form.useForm<AdminModelProvider>();
    const [routeForm] = Form.useForm<AdminModelRoute>();
    const [variantForm] = Form.useForm<AdminModelVariant>();
    const load = async () => { if (!token) return; const [nextProviders, nextModels, nextRoutes, nextVariants] = await Promise.all([fetchAdminModelProviders(token), fetchModelMarket(), fetchAdminModelRoutes(token), fetchAdminModelVariants(token)]); setProviders(nextProviders); setModels(nextModels); setRoutes(nextRoutes); setVariants(nextVariants); };
    useEffect(() => { void load(); }, [token]);
    const saveProvider = async () => { const values = await providerForm.validateFields(); await saveAdminModelProvider(token!, values); message.success("供应商已保存"); setProviderOpen(false); providerForm.resetFields(); await load(); };
    const saveRoute = async () => { const values = await routeForm.validateFields(); const variant = variants.find((item) => item.id === values.variantId); await saveAdminModelRoute(token!, {...values,modelId:variant?.modelId || values.modelId}); message.success("模型线路已保存"); setRouteOpen(false); routeForm.resetFields(); await load(); };
    const saveVariant = async () => { const values = await variantForm.validateFields(); await saveAdminModelVariant(token!,values); message.success("模型档位已保存，模型广场会自动更新"); setVariantOpen(false); variantForm.resetFields(); await load(); };
    return <div className="p-6"><Card title="模型、档位与上游线路" extra={<Space><Button onClick={() => void load()}>刷新</Button><Button onClick={() => { if (providers[0]) providerForm.setFieldsValue(providers[0]); setProviderOpen(true); }}>配置四家上游</Button><Button type="primary" onClick={() => setRouteOpen(true)}>配置档位线路</Button></Space>}>
        <Tabs items={[
            { key: "models", label: `模型卡 ${models.length}`, children: <Table rowKey="id" dataSource={models} pagination={{ pageSize: 20 }} columns={[{ title: "自有 ID", dataIndex: "id" }, { title: "前台名称", dataIndex: "name" }, { title: "分类", dataIndex: "category" }, { title: "档位数", render: (_:unknown,item:MarketModelCard)=>item.variants.length }, { title: "状态", render: (_: unknown, item: MarketModelCard) => <Tag color={item.available ? "success" : "default"}>{item.available ? "已有可用档位" : "待接入"}</Tag> }]} /> },
            { key: "variants", label: `档位与售价 ${variants.length}`, children: <Table rowKey="id" dataSource={variants} pagination={{pageSize:20}} columns={[{title:"模型",dataIndex:"modelId",render:(value:string)=>models.find((item)=>item.id===value)?.name||value},{title:"档位",dataIndex:"name"},{title:"定价",render:(_:unknown,item:AdminModelVariant)=>item.pricingMode==="fixed"&&typeof item.priceCents==="number"?`¥${(item.priceCents/100).toFixed(2)} ${item.billingUnit}`:item.pricingMode==="dynamic"?item.priceFormula:"暂不上架"},{title:"状态",dataIndex:"enabled",render:(value:boolean)=><Tag color={value?"success":"default"}>{value?"上架":"下架"}</Tag>},{title:"操作",render:(_:unknown,item:AdminModelVariant)=><Button size="small" onClick={()=>{variantForm.setFieldsValue(item);setVariantOpen(true);}}>修改售价/状态</Button>}]} /> },
            { key: "providers", label: `供应商 ${providers.length}`, children: <Table rowKey="id" dataSource={providers} columns={[{ title: "名称", dataIndex: "name" }, { title: "代码", dataIndex: "code" }, { title: "Base URL", dataIndex: "baseUrl" }, { title: "服务器 Secret", dataIndex: "hasApiKey", render: (value: boolean) => <Tag color={value ? "success" : "warning"}>{value ? "已配置" : "未配置"}</Tag> }, { title: "状态", dataIndex: "enabled", render: (value: boolean) => <Tag color={value ? "success" : "default"}>{value ? "启用" : "停用"}</Tag> }, { title: "操作", render: (_: unknown, item: AdminModelProvider) => <Button size="small" onClick={() => { providerForm.setFieldsValue(item); setProviderOpen(true); }}>编辑</Button> }]} /> },
            { key: "routes", label: `线路 ${routes.length}`, children: <Table rowKey="id" dataSource={routes} columns={[{ title: "模型档位", dataIndex: "variantId", render:(value:string)=>{const item=variants.find((variant)=>variant.id===value);return item?`${models.find((model)=>model.id===item.modelId)?.name||item.modelId} / ${item.name}`:value;} }, { title: "供应商", dataIndex: "providerId", render: (value: string) => providers.find((item) => item.id === value)?.name || value }, { title: "实际上游 ID", dataIndex: "upstreamModelId" }, { title: "顺序", dataIndex: "priority" }, { title: "状态", dataIndex: "enabled", render: (value: boolean) => <Tag color={value ? "success" : "default"}>{value ? "启用" : "停用"}</Tag> }, { title: "操作", render: (_: unknown, item: AdminModelRoute) => <Button size="small" onClick={() => { routeForm.setFieldsValue(item); setRouteOpen(true); }}>编辑</Button> }]} /> },
        ]} />
    </Card>
    <Modal title="上游供应商（密钥使用服务器 Secret）" open={providerOpen} onCancel={() => setProviderOpen(false)} onOk={() => void saveProvider()}><Form form={providerForm} layout="vertical" initialValues={{ enabled: false, priority: 10, timeout: 300 }}><Form.Item name="id" hidden><Input /></Form.Item><Form.Item name="name" label="名称" rules={[{ required: true }]}><Select options={providers.map((item)=>({label:item.name,value:item.name}))} /></Form.Item><Form.Item name="code" label="代码" rules={[{ required: true }]}><Input disabled /></Form.Item><Form.Item name="baseUrl" label="Base URL" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="API Key"><div className="rounded-lg border border-stone-200 p-3 text-sm text-stone-500 dark:border-stone-700">请在 Render 或服务器环境变量中配置对应的 <code>MODEL_PROVIDER_*_API_KEY</code>。网页和数据库都不保存明文 Key。</div></Form.Item><Form.Item name="priority" label="优先级"><InputNumber min={1} /></Form.Item><Form.Item name="timeout" label="超时秒数"><InputNumber min={30} /></Form.Item><Form.Item name="enabled" label="启用" valuePropName="checked"><Switch /></Form.Item></Form></Modal>
    <Modal title="模型档位售价" open={variantOpen} onCancel={()=>setVariantOpen(false)} onOk={()=>void saveVariant()}><Form form={variantForm} layout="vertical"><Form.Item name="id" hidden><Input /></Form.Item><Form.Item name="modelId" hidden><Input /></Form.Item><Form.Item name="name" label="档位"><Input disabled /></Form.Item><Form.Item name="pricingMode" label="定价方式"><Select options={[{label:"固定人民币",value:"fixed"},{label:"实际成本动态加价",value:"dynamic"},{label:"暂不上架",value:"disabled"}]} /></Form.Item><Form.Item name="priceCents" label="用户售价（人民币分）"><InputNumber min={0} precision={0} className="w-full" /></Form.Item><Form.Item name="priceFormula" label="动态定价公式"><Input placeholder="例如：实际成本×1.08" /></Form.Item><Form.Item name="billingUnit" label="计费单位"><Input /></Form.Item><Form.Item name="enabled" label="上架" valuePropName="checked"><Switch /></Form.Item></Form></Modal>
    <Modal title="模型档位线路" open={routeOpen} onCancel={() => setRouteOpen(false)} onOk={() => void saveRoute()}><Form form={routeForm} layout="vertical" initialValues={{ enabled: false, priority: 1, protocol: "custom" }}><Form.Item name="id" hidden><Input /></Form.Item><Form.Item name="modelId" hidden><Input /></Form.Item><Form.Item name="variantId" label="模型档位" rules={[{ required: true }]}><Select showSearch options={variants.map((item) => ({ label: `${models.find((model)=>model.id===item.modelId)?.name||item.modelId} / ${item.name}`, value: item.id }))} /></Form.Item><Form.Item name="providerId" label="供应商" rules={[{ required: true }]}><Select options={providers.map((item) => ({ label: item.name, value: item.id }))} /></Form.Item><Form.Item name="upstreamModelId" label="实际上游 ID" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="protocol" label="协议"><Select options={[{ label: "OpenAI 兼容", value: "openai" }, { label: "WaveSpeed", value: "wavespeed" }, { label: "自定义", value: "custom" }]} /></Form.Item><Form.Item name="priority" label="线路顺序"><InputNumber min={1} /></Form.Item><Form.Item name="enabled" label="启用" valuePropName="checked"><Switch /></Form.Item></Form></Modal>
    </div>;
}
